import { StyleSheet, Platform } from 'react-native';

export const registerStyles = StyleSheet.create({
  wrapper: {
    flex: 1,
    position: 'relative',
  },
  svgBackground: {
    position: 'absolute',
    top: -60,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    zIndex: 0,
  },
  scrollContainer: {
    flexGrow: 1,
    backgroundColor: 'transparent',
    minHeight: '100%',
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
    minHeight: '100%',
    zIndex: 1,
  },
  // cardWrapper keeps sizing but no visible background so elements sit on the SVG
  cardWrapper: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: 'transparent',
    borderRadius: 0,
    overflow: 'visible',
    alignSelf: 'center',
  },
  authCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: 'transparent',
    borderRadius: 0,
    overflow: 'visible',
    alignSelf: 'center',
  },
  authHeader: {
    backgroundColor: 'transparent',
    paddingTop: 20,
    paddingBottom: 8,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    marginBottom: 8,
  },
  authHeaderInner: {
    alignItems: 'center',
    gap: 16,
  },
  avatarCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 2,
    borderColor: '#fff',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarEmoji: {
    fontSize: 34,
    lineHeight: 34,
  },
  authTitle: {
    fontSize: 44,
    fontWeight: '600',
    color: '#ffffff',
  },
  authBody: {
    paddingTop: 54,
    paddingBottom: 28,
    paddingHorizontal: 28,
  },
  fieldGroup: {
    marginBottom: 18,
  },
  fieldLabel: {
    fontSize: 13.5,
    color: '#111',
    marginBottom: 4,
    fontWeight: '500',
  },
  inputWrapper: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e7f2fa',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#143c6a',
    paddingVertical: 10,
    paddingHorizontal: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.03,
        shadowRadius: 12,
      },
      android: {
        elevation: 1,
      },
    }),
  },
  iconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f3f3f3',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  iconText: {
    fontSize: 18,
  },
  input: {
    flex: 1,
    fontSize: 14.5,
    color: '#380000',
    padding: 0,
  },
  cardTitle: {
    fontSize: 40,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
    marginTop: 22,
    marginBottom: 38,
  },
  primaryBtn: {
    width: '100%',
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginTop: 26,
    backgroundColor: 'rgba(0, 47, 255, 0.6)',
    borderWidth: 0,
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.12,
        shadowRadius: 18,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  primaryBtnText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  authFooter: {
    paddingVertical: 18,
    paddingHorizontal: 28,
    alignItems: 'center',
    marginTop: -30,
  },
  footerText: {
    fontSize: 13,
    color: '#000000',
  },
  footerLink: {
    fontWeight: '600',
    color: '#000dff',
  },
});