import { StyleSheet, Platform } from 'react-native';

export const forgotStyles = StyleSheet.create({
  wrapper: {
    flex: 1,
    position: 'relative',
    backgroundColor: 'transparent',
  },
  svgBackground: {
    position: 'absolute',
    top: -60,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    zIndex: 0,
  },
  scrollContainer: {
    flexGrow: 1,
    backgroundColor: 'transparent',
    minHeight: '100%',
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
    minHeight: '100%',
    zIndex: 1,
  },
  authCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: 'transparent',
    borderRadius: 0,
    overflow: 'visible',
    alignSelf: 'center',
  },
  cardTitle: {
    fontSize: 40,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
    marginTop: -40,
    marginBottom: 8,
  },
  description: {
    fontSize: 13,
    color: '#ffffff',
    textAlign: 'center',
    paddingHorizontal: 20,
    marginBottom: 20,
    lineHeight: 20,
  },
  authBody: {
    paddingTop:144,
    paddingBottom: 28,
    paddingHorizontal: 28,
  },
  fieldGroup: {
    marginBottom: 18,
  },
  fieldLabel: {
    fontSize: 13.5,
    color: '#111',
    marginBottom: 4,
    fontWeight: '500',
  },
  inputWrapper: {
    marginTop:4,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e7f2fa',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#143c6a',
    paddingVertical: 10,
    paddingHorizontal: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.03,
        shadowRadius: 12,
      },
      android: {
        elevation: 1,
      },
    }),
  },
  iconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f3f3f3',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  iconText: {
    fontSize: 18,
  },
  input: {
    flex: 1,
    fontSize: 14.5,
    color: '#380000',
    padding: 0,
  },
  primaryBtn: {
    width: '100%',
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginTop: 26,
    backgroundColor: '#FF0000',
    borderWidth: 0,
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#c9d2f1',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.12,
        shadowRadius: 18,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  primaryBtnText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  linkText: {
    fontSize: 13,
    color: '#FF0000',
    textAlign: 'center',
    marginTop: 16,
    fontWeight: '500',
  },
  authFooter: {
    paddingVertical: 18,
    paddingHorizontal: 28,
    alignItems: 'center',
    marginTop: 20,
  },
  footerText: {
    fontSize: 13,
    color: '#000000',
  },
  footerLink: {
    fontWeight: '600',
    color: '#FF0000',
  },
});
